### PR TITLE
PR review suggestions

### PR DESCRIPTION
**Pull request by cmccandless**
Consider this my review for #2140. I've reworked what you had to decrease the density and improve readability. It *is* a little longer, but IMO it is significantly more readable. I welcome your counter-feedback.

### CODE REVIEW

**Comment by dvermd** [comment]
I see that you're using assertAlmost for testing exponentials and euler among others. 
That's clever, and was previously done for testing divide for example.

I'm having a second thought on this, as this rely on `__eq__` to be implemented first by the student which might not be the function he/she chose to implement first.

**Comment by cmccandless** [comment]
> I'm having a second thought on this, as this rely on __eq__ to be implemented first by the student which might not be the function he/she chose to implement first.

If the student is following TDD principles as intended, they won't have much of a choice, and will have to implement that method early in the process.

**Comment by dvermd** [comment]
> 
> If the student is following TDD principles as intended, they won't have much of a choice, and will have to implement that method early in the process.

You're right on this point. In this particular exercise, the `__eq__` function is only to be implemented as additional_tests. I don't have that much step back on this track to choose the better approch.

Anyhow, you're code is much cleaner and easier to read/maintain than mine was. Congrats.

**Comment by cmccandless** [comment]
If you like my suggestions, go ahead and merge this PR. Your PR in the official repo will automatically update.

**Pull request merged**
